# --- SERVIDOR DEV ---
server.port=8080

# --- BASE DE DATOS DEV (Local) ---
# En desarrollo podés poner las credenciales directo (es tu máquina local)
spring.datasource.url=jdbc:postgresql://localhost:5432/mariano_defea_dev
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# --- LOGS DEV ---
# Imprime el código SQL que genera Hibernate (SÚPER útil en dev)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG