# --- SERVIDOR PROD ---
server.address=${SERVER_ADRESS}
server.port=${SERVER_PORT}

# --- BASE DE DATOS PROD ---
# Usamos las variables de entorno del servidor real
spring.datasource.url=${SPRING_DATASOURCE_DB_URL}
spring.datasource.username=${SPRING_DATASOURCE_USER}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# MUY IMPORTANTE EN PROD: Hibernate no debe alterar tablas, solo Flyway lo hace.
spring.jpa.hibernate.ddl-auto=validate

# --- LOGS PROD ---
# Apagamos el show-sql y los logs de debug para no saturar el servidor
spring.jpa.show-sql=false
logging.level.org.springframework.security=WARN